# Generated by Django 4.1.5 on 2023-02-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fridges',
            fields=[
                ('fridge_id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=256)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
