# Generated by Django 4.1.5 on 2023-02-12 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_fridges'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='server.listing'),
        ),
        migrations.AddField(
            model_name='listing',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Buyer', to='server.user'),
        ),
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='messages',
            name='date_sent',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Seller', to='server.user'),
        ),
    ]
