# Generated by Django 4.1.5 on 2023-02-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_chat_listing_listing_buyer_listing_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
