# Generated by Django 4.0 on 2023-02-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_alter_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='interested',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
