# Generated by Django 4.0 on 2023-03-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_remove_chat_review_count_chat_buyer_reviewed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(null=True, upload_to='profile_images'),
        ),
    ]
