# Generated by Django 4.0 on 2023-03-20 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_following'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
